-- CreateTable
CREATE TABLE "Poem" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "title" TEXT NOT NULL,
    "author" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "datePublished" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);
